---
Name: foxystripeconfig
---
SilverStripe\Security\Member:
  extensions:
    - Dynamic\FoxyStripe\ORM\CustomerExtension

PageController:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripePageExtension

SilverStripe\Forms\DateField:
  default_config:
    showcalendar: true

SilverStripe\Forms\FormField:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripeProductFormFieldExtension

SilverStripe\Core\Injector\Injector:
  TimeZoneData:
    properties:
      format: '%Region/%Name'