---
Name: foxystripeconfig
---
SilverStripe\Security\Member:
  extensions:
    - Dynamic\FoxyStripe\ORM\CustomerExtension
  customer_map:
    int:
      customer_id: 'Customer_ID'
    string:
      customer_first_name: 'FirstName'
      customer_last_name: 'Surname'
      customer_email: 'Email'
      customer_password: 'Password'
      customer_password_salt: 'Salt'
      customer_password_hash_type: 'PasswordEncryption'

PageController:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripePageExtension

SilverStripe\Forms\FormField:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripeProductFormFieldExtension

SilverStripe\Core\Injector\Injector:
  TimeZoneData:
    properties:
      format: '%Region/%Name'

