---
Name: foxystripeconfig
---
SilverStripe\Security\Member:
  extensions:
    - Dynamic\FoxyStripe\ORM\CustomerExtension
  password_logging_enabled: false

PageController:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripePageExtension

SilverStripe\Forms\FormField:
  extensions:
    - Dynamic\FoxyStripe\ORM\FoxyStripeProductFormFieldExtension

SilverStripe\Core\Injector\Injector:
  TimeZoneData:
    properties:
      format: '%Region/%Name'

'SilverStripe\Security\PasswordEncryptor':
  encryptors:
    bcrypt:
      'Dynamic\FoxyStripe\Security\PasswordEncryptor_BCrypt':
