---
Name: foxystripeconfig
---
SiteConfig:
  extensions:
    - FoxyStripeSiteConfig
Member:
  extensions:
    - CustomerExtension
DateField:
  default_config:
    showcalendar: true
FoxyStripeProduct:
  extensions:
    - VersionedDataObject
    - DataObjectPagifyDataExtension