---
Name: foxystripeconfig
---
SiteConfig:
  extensions:
    - FoxyStripeSiteConfig
Member:
  extensions:
    - FoxyStripeCustomerExtension
DateField:
  default_config:
    showcalendar: true
FormField:
  extensions:
    - FoxyStripeProductFormFieldExtension