---
Name: foxystriperoutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'generateCache//$Action/$ID/$Name': 'FoxyStripeCache_Controller'
    'foxycart//$Action/$ID/$Name': 'FoxyCart_Controller'