---
Name: foxystriperoutes
After: framework/routes#coreroutes
---
Director:
  rules:
    'generateCache//$Action/$ID/$Name': 'FoxyStripeCache_Controller'
    'order-collection//$Action/$ID/$Name': 'FoxyCartDataFeedCollector'